### ISSUE TITLE
PUT userID into project

### ISSUE THREAD

**Issue by wiepke** [juliandehne/competence-database#42]
When I try to put a new user with the fictional character name "Axel" into the project "12345" via my website, I get:
<html><head><title>Apache Tomcat/7.0.61 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - java.lang.NullPointerException</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>java.lang.NullPointerException</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: java.lang.NullPointerException
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:392)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:303)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
	uzuzjmd.competence.analytics.DurationLogFilter.doFilter(DurationLogFilter.java:31)
</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException
	uzuzjmd.competence.service.rest.GroupApiImpl.createPreferences(GroupApiImpl.java:43)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:303)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
	uzuzjmd.competence.analytics.DurationLogFilter.doFilter(DurationLogFilter.java:31)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.61 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.61</h3></body></html>

**Comment by juliandehne** [comment]
server was on standby at the time. Should be ok now.
