### ISSUE TITLE
Schnittstelle gibt keine Ausgabe

### ISSUE THREAD

**Issue by wiepke** [juliandehne/competence-database#45]
Es ist die User-ID einzugeben und eine Kurs-ID soll ausgegeben werden mit curl 
-X GET --header 'Accept: application/json' 'http://fleckenroller.cs.uni-potsdam.de/app/competence-database-prod/api1/users/Axel/courses'
Es gibt jedoch für alle getesteten Nutzer ein leeres array zurück und wirft keinen Fehler.

**Comment by juliandehne** [comment]
Bei zweiter Betrachtung ist die Schnittstelle kommentiert mit " get courses from user in lms".  Überlege mir einen Fix.
